name: WebdriverIO Tests

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y nodejs npm
        npm install
    - name: Run Tests
      run: |
        npx wdio wdio.conf.js
